version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk
    steps:
      - checkout
      - restore_cache:
          key: gradle-v1-{{ checksum "build.gradle" }}
      - run:
          name: Set Java to 17
          command: |
            sudo update-alternatives --set java /usr/local/openjdk-17/bin/java
            java -version
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: gradle-v1-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file